version: "3"

services:
  server:
    platform: linux/x86_64
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env.dev
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  client:
    container_name: client
    build: ./client
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "3000:3000"
    volumes:
      - ./client:/src
    env_file:
      - .env.dev
    command: >
      sh -c "npm install -g npm@latest && npm install && npm run dev"
    depends_on:
      - server
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.dev

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
